spring.application.name=demo
server.port=8080
spring.datasource.url=jdbc:postgresql://192.168.2.47:5432/Freshers_Training
spring.datasource.username=freshers_training_user
spring.datasource.password=Appzillon@001

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
